services:
  - type: web
    name: culture-laravel
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
